name: CI/CD Deploy Java App to Tomcat10 on EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3️⃣ Build WAR file
      - name: Build WAR file
        run: mvn clean package -DskipTests

      # 4️⃣ Copy WAR file to EC2
      - name: Copy WAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/ROOT.war"
          target: "/tmp/ROOT.war"

      # 5️⃣ Deploy WAR to Tomcat10
      - name: Deploy WAR on Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Stopping Tomcat..."
            sudo systemctl stop tomcat10 || true

            echo "Removing old ROOT app..."
            sudo rm -rf /var/lib/tomcat10/webapps/ROOT /var/lib/tomcat10/webapps/ROOT.war

            echo "Moving new WAR..."
            sudo mv /tmp/ROOT.war /var/lib/tomcat10/webapps/
            sudo chown tomcat:tomcat /var/lib/tomcat10/webapps/ROOT.war
            sudo chmod 644 /var/lib/tomcat10/webapps/ROOT.war

            echo "Starting Tomcat..."
            sudo systemctl start tomcat10

            echo "Waiting 20 seconds for WAR to unpack..."
            sleep 20

            echo "Deployed apps:"
            ls -lh /var/lib/tomcat10/webapps/

            sudo systemctl status tomcat10 --no-pager
            echo "✅ Deployment completed successfully!"
