name: CI/CD Deploy Java App to Tomcat10 on EC2

# Trigger deployment on push to master branch
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3️⃣ Build WAR file
      - name: Build WAR file
        run: mvn clean package -DskipTests

      # 4️⃣ Verify WAR file exists
      - name: Verify WAR file
        run: |
          if [ ! -f "target/ROOT.war" ]; then
            echo "ERROR: ROOT.war not found in target directory"
            exit 1
          fi
          ls -lh target/ROOT.war

      # 5️⃣ Copy WAR file to EC2
      - name: Copy WAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/ROOT.war"
          target: "/tmp/ROOT.war"

      # 6️⃣ Deploy WAR on Tomcat
      - name: Deploy WAR on Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "=== Starting Deployment ==="
            
            echo "1. Stopping Tomcat..."
            sudo systemctl stop tomcat10 || true
            
            echo "2. Cleaning up old deployment..."
            sudo rm -rf /var/lib/tomcat10/webapps/ROOT
            sudo rm -rf /var/lib/tomcat10/webapps/ROOT.war
            
            echo "3. Verifying source WAR file exists..."
            if [ ! -f "/tmp/ROOT.war" ]; then
              echo "ERROR: /tmp/ROOT.war not found!"
              exit 1
            fi
            ls -lh /tmp/ROOT.war
            
            echo "4. Copying WAR to webapps directory..."
            sudo cp /tmp/ROOT.war /var/lib/tomcat10/webapps/
            
            echo "5. Setting permissions..."
            sudo chown tomcat:tomcat /var/lib/tomcat10/webapps/ROOT.war
            sudo chmod 644 /var/lib/tomcat10/webapps/ROOT.war
            
            echo "6. Verifying WAR file in webapps..."
            ls -lh /var/lib/tomcat10/webapps/
            file /var/lib/tomcat10/webapps/ROOT.war
            
            echo "7. Creating ROOT directory..."
            sudo mkdir -p /var/lib/tomcat10/webapps/ROOT
            sudo chown tomcat:tomcat /var/lib/tomcat10/webapps/ROOT
            sudo chmod 755 /var/lib/tomcat10/webapps/ROOT
            
            echo "8. Extracting WAR file..."
            sudo -u tomcat unzip -o /var/lib/tomcat10/webapps/ROOT.war -d /var/lib/tomcat10/webapps/ROOT/
            
            echo "9. Setting permissions for extracted files..."
            sudo chown -R tomcat:tomcat /var/lib/tomcat10/webapps/ROOT/
            sudo chmod -R 755 /var/lib/tomcat10/webapps/ROOT/
            
            echo "10. Starting Tomcat..."
            sudo systemctl start tomcat10
            
            echo "11. Waiting for startup..."
            sleep 30
            
            echo "12. Verifying deployment:"
            ls -la /var/lib/tomcat10/webapps/
            sudo systemctl status tomcat10 --no-pager
            
            echo "=== Deployment Completed Successfully ==="
